from django import forms
from django.forms import ModelForm
from .models import Reservation
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class ReservationForm(forms.ModelForm):
    completed = models.BooleanField(default=False)
    class Meta:
        model = Reservation
        fields = [
            'first_name_reserve',
            'last_name_reserve',
            'email_address',
            'contact_number_reserve',
            'facebook_url',
            'street_number',
            'baranggay',
            'zip_code',
            'municipality',
            'province',
            'indoor_shoot',
            'outdoor_shoot',
            'comment_request',
            'wedding_pre_nuptial',
            'pre_debut',
            'toddler',
            'pre_birthday',
            'maternity',
            'family_portrait',
            'graduation_photo',
            'barkada_shoot',
            'wedding_package1',
            'wedding_package2',
            'wedding_package3',
            'debut_package1',
            'debut_package2',
            'debut_package3',
            'toddler_package1',
            'toddler_package2',
            'toddler_package3',
            'pre_birthday_package1',
            'pre_birthday_package2',
            'pre_birthday_package3',
            'maternity_package1',
            'maternity_package2',
            'maternity_package3',
            'family_portrait_package1',
            'family_portrait_package2',
            'family_portrait_package3',
            'graduation_package1',
            'graduation_package2',
            'graduation_package3',
            'barkada_package1',
            'barkada_package2',
            'barkada_package3',
            'additional',
            'selection2',
            'selection3',
            'selection4',
            'selection5',
            'selection6',
            'selection7',
            'selection8',
            'selection1',
            'flashdrive',
            'yes',
            'no',
            'comment_request',
            'wedding',
            'debut',
            'baptismal',
            'indoor_date',
            'indoor_radio1',
            'indoor_radio2',
            'indoor_radio3',
            'indoor_radio4',
            'indoor_radio5',
            'number_of_people',
            'outdoor_date',
            'outdoor_time',
            'outdoor_end',
            'events_location',
            'events_description',
            'check_terms',
            'verify_image',
            'status',
            'completed',
            'pending',
            'reserved',
            'declined',
            'wedding',
            'debut',
            'baptismal',
            'birthday',
            'church_wedding',
            'civil_wedding',
            'wedding_event',
            'prenup_outdoor',
            'video_package',
            'package_outdoor',
            'package2_outdoor',
            'video_package2',
            'photo_video',
            'photo_video_2',
            'pre_debut_outdoor',
            'debut_outdoor',
            'pre_debut_outdoor1',
            'pre_debut_outdoor2',
            'pre_debut_outdoor3',
            'package_debut1',
            'package_debut2',
            'package_debut3',
            'baptismal_outdoor1',
            'baptismal_outdoor2',
            'baptismal_outdoor3',
            'birthday_outdoor1',
            'birthday_outdoor2',
            'birthday_outdoor3',
            'v1',
            'v2',
            'v3',
            'v4',
            'v5',
            'v6',
        

        
        ]
        include = ['user']
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','phone_num','avatar']

